python create_manifest.py D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-02_4 D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-02_4 1
python create_manifest.py D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-01_71 D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-01_71 1
python create_manifest.py D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-04_8 D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-04_8 1
python create_manifest.py D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-05_9 D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-05_9 1
python create_manifest.py D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-06_11 D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-06_11 1
python create_manifest.py D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-08_14 D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-08_14 1
python create_manifest.py D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-09_15 D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-09_15 1
python create_manifest.py D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-10_16 D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-10_16 1
python create_manifest.py D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-11_17 D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-11_17 1
python create_manifest.py D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-12_20 D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-12_20 1
python create_manifest.py D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-13_22 D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-13_22 1
python create_manifest.py D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-14_23 D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-14_23 1
python create_manifest.py D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-15_25 D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-15_25 1
python create_manifest.py D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-16_28 D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-16_28 1
python create_manifest.py D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-17_29 D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-17_29 1
python create_manifest.py D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-18_30 D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-18_30 1
python create_manifest.py D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-19_35 D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-19_35 1
python create_manifest.py D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-20_37 D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-20_37 1
python create_manifest.py D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-21_43 D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-21_43 1
python create_manifest.py D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-22_44 D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-22_44 1
python create_manifest.py D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-23_46 D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-23_46 1
python create_manifest.py D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-24_48 D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-24_48 1
python create_manifest.py D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-25_52 D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-25_52 1
python create_manifest.py D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-26_53 D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-26_53 1
python create_manifest.py D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-27_54 D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-27_54 1
python create_manifest.py D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-28_55 D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-28_55 1
python create_manifest.py D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-29_57 D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-29_57 1
python create_manifest.py D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-30_59 D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-30_59 1
python create_manifest.py D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-31_60 D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-31_60 1
python create_manifest.py D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-32_61 D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-32_61 1
python create_manifest.py D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-33_64 D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-33_64 1
python create_manifest.py D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-34_65 D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-34_65 1
python create_manifest.py D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-35_66 D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-35_66 1
python create_manifest.py D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-36_68 D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-36_68 1
python create_manifest.py D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-03_70 D:\eMammal\From_Agouti\Zofin\processed\CT-ZFN-1-03_70 1